apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: grpctest
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/cloudylabs-public/grpctest:0.1.2
            resources:
              limits:
                cpu: "1"
